/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
import { useTranslation } from 'react-i18next'

import { getUserAgreement } from './api'
import { LegalDocument } from './legal-document'

export function UserAgreement() {
  const { t } = useTranslation()
  return (
    <LegalDocument
      title={t('Terms of Service')}
      queryKey='user-agreement'
      fetchDocument={getUserAgreement}
      description={t(
        'Review the terms that apply when accessing the token-hub website, account features, and AI API gateway.'
      )}
      canonicalPath='/user-agreement'
      defaultContent={
        <>
          <section>
            <h2>{t('1. Agreement')}</h2>
            <p>
              {t(
                'By accessing token-hub, creating an account, or using an API endpoint, you agree to these Terms of Service and the Privacy Policy. If you use the service for an organization, you represent that you are authorized to accept these terms for that organization.'
              )}
            </p>
          </section>

          <section>
            <h2>{t('2. Service')}</h2>
            <p>
              {t(
                'token-hub provides an AI API gateway, account and credential management, routing, usage records, and related operational tools. Features, upstream providers, limits, and availability may change over time.'
              )}
            </p>
          </section>

          <section>
            <h2>{t('3. Accounts and credentials')}</h2>
            <p>
              {t(
                'You must provide accurate account information, protect passwords and API keys, use appropriate access controls, and promptly report suspected compromise. You are responsible for activity performed with your account or credentials unless applicable law provides otherwise.'
              )}
            </p>
          </section>

          <section>
            <h2>{t('4. Acceptable use')}</h2>
            <p>{t('You must not use the service to:')}</p>
            <ul>
              <li>
                {t(
                  'Violate applicable law, intellectual property rights, privacy rights, or the rights of another person.'
                )}
              </li>
              <li>
                {t(
                  'Distribute malware, attack systems, evade security controls, probe without authorization, or disrupt the service or an upstream provider.'
                )}
              </li>
              <li>
                {t(
                  'Resell, share, or automate access in a manner that violates the applicable plan, provider terms, or published limits.'
                )}
              </li>
              <li>
                {t(
                  'Submit content you do not have the right to process or attempt to use the service for fraud, abuse, or deception.'
                )}
              </li>
            </ul>
          </section>

          <section>
            <h2>{t('5. Third-party AI providers')}</h2>
            <p>
              {t(
                'Requests may be processed by third-party AI providers. Their models, output, availability, data handling, and acceptable-use rules are outside token-hub’s control and may be governed by separate terms. You are responsible for reviewing provider-specific requirements that apply to your use.'
              )}
            </p>
          </section>

          <section>
            <h2>{t('6. Charges, quotas, and refunds')}</h2>
            <p>
              {t(
                'Displayed prices, quotas, billing units, and payment rules apply at the time of use. Usage records generated by the service are used to calculate consumption. Except where required by law or expressly stated by the operator, purchased credits and completed usage charges are non-refundable.'
              )}
            </p>
          </section>

          <section>
            <h2>{t('7. Intellectual property and open source')}</h2>
            <p>
              {t(
                'You retain rights in content you lawfully submit. The token-hub distribution is based on the open-source New API project, and New API and its contributors retain their respective copyrights. Open-source components remain governed by their applicable licenses, including the GNU Affero General Public License v3.0 where applicable.'
              )}
            </p>
            <p>
              <a
                href='https://github.com/w116991178-png/token-hub'
                target='_blank'
                rel='noopener noreferrer'
                className='text-[#4f5600] underline underline-offset-4 dark:text-[#d9ff52]'
              >
                {t('token-hub source code')}
              </a>{' '}
              ·{' '}
              <a
                href='https://github.com/QuantumNous/new-api'
                target='_blank'
                rel='noopener noreferrer'
                className='text-[#4f5600] underline underline-offset-4 dark:text-[#d9ff52]'
              >
                {t('New API upstream project')}
              </a>
            </p>
          </section>

          <section>
            <h2>{t('8. Availability and changes')}</h2>
            <p>
              {t(
                'The service is provided on an as-available basis. Maintenance, provider failures, network conditions, policy changes, or security events may interrupt service. The operator may change, limit, or discontinue features and will provide notice when reasonably required.'
              )}
            </p>
          </section>

          <section>
            <h2>{t('9. Suspension and termination')}</h2>
            <p>
              {t(
                'Access may be limited or suspended to protect users, providers, or the service; respond to legal requirements; prevent abuse; address non-payment; or enforce these terms. You may stop using the service at any time.'
              )}
            </p>
          </section>

          <section>
            <h2>{t('10. Disclaimers and liability')}</h2>
            <p>
              {t(
                'AI output may be inaccurate, incomplete, or unsuitable. You must evaluate output before relying on it, especially for high-impact decisions. To the extent permitted by law, the service is provided without implied warranties, and liability is limited to the maximum extent permitted by applicable law.'
              )}
            </p>
          </section>

          <section>
            <h2>{t('11. Changes and contact')}</h2>
            <p>
              {t(
                'These terms may be updated as the service changes. Continued use after an effective update constitutes acceptance where permitted by law. Questions may be directed through the support channel published by the site operator or the token-hub repository.'
              )}
            </p>
          </section>
        </>
      }
    />
  )
}
